# Getting Flutter ready...
#
# This file is autogenerated by `flutter create` command to fasttrack development on
# Flutter Windows desktop platform.
#
# Learn more: https://github.com/flutter/flutter/wiki/Developing-for-Windows

windows:
  # The number of milliseconds (millisecond precision) to wait after
  # the last `PointerMove` event before activating the hover state (if it exists).
  hover_hysteresis_duration: 100

  # The maximum aggregate number of pixels the cursor may move by within the
  # hover_hysteresis_duration before the hover state will be deactivated.
  hover_hysteresis_distance: 5.0
